# Generated by Django 4.2.7 on 2023-12-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BrandModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quntity', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='CarModel/media/uploads')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandModel.createbrand')),
            ],
        ),
    ]
