# Generated by Django 4.2.7 on 2023-12-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarModel', '0003_buying_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='CModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarModel.carmodel'),
        ),
    ]
