# Generated by Django 4.2.7 on 2023-12-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarModel', '0004_alter_comment_cmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='CModel',
        ),
    ]
