# Generated by Django 4.2.7 on 2023-12-09 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='task_assign_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Enter task assignment date', null=True),
        ),
    ]
