-- In here we will how to make join table without use of JOIN keyword or qurey in here
SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME, DEPARTMENTS.DEPARTMENT_ID
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;






-- EXAMPLES OF THE JOIN QUREY E TO A

-- QUSTION NO:1) PRINT THE EMPLOYEE NAME AND THE NAME OF THE MANAGER NAME OF THE EMPLOYEE
SELECT E.FIRST_NAME AS EMPLOYEE_NAME , M.FIRST_NAME AS MANAGER_NAME
FROM EMPLOYEES AS M
	JOIN EMPLOYEES AS E
    ON M.EMPLOYEE_ID = E.MANAGER_ID;

-- QUSTION NO:2) PRINT THOSE DEPARTMENT NAME WHOSE DON'T HAVE ANY EMPLOYEES
 
SELECT DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
	LEFT JOIN EMPLOYEES
ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;

-- QUSTION NO:3) PRINT THE FIRST NAME , SALARY, AND LESS SALAY OF THE AVARAGE
SELECT EMPLOYEES.FIRST_NAME,
	   EMPLOYEES.SALARY,
       (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID) - EMPLOYEES.SALARY AS LESS_AVARAGE
FROM EMPLOYEES
	JOIN DEPARTMENTS
		ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
        
-- QUSTION NO:4) PRINT THE NAME OF THE DEPARTMENT, WHOSE MIN SALARY IS LESS THEN 5000

SELECT DEPARTMENTS.DEPARTMENT_NAME , MIN(SALARY)
FROM EMPLOYEES
	JOIN DEPARTMENTS
		ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY  DEPARTMENT_NAME
HAVING MIN(SALARY) < 5000
