-- IN HERE WE WILL SEE SOME ADVANCEED QUERRY
-- FIRST ONE IS FIND THE SECOND HIGHEST SALARY HOW MUCH AND SHOW THE INFO OF THE EMPLOYEE
-- THERE ARE TWO WAY TO SOLVE THE PROBLEM HERE IS THE FIRST WAY BUT NOT GOOD WAY 
SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1, 1;

-- ANOTHER
-- MAIN QUERY
SELECT *
FROM EMPLOYEES
WHERE SALARY = ( -- SUBQUREY 
				SELECT SALARY
				FROM EMPLOYEES
				ORDER BY SALARY DESC
				LIMIT 1, 1);
                
-- HERE IS THE SECOND WAY AND THIS THE CURRECT WAY TO DO THE WORK
-- MAIN QUERY
SELECT *
FROM EMPLOYEES
WHERE SALARY = (-- SUB QUREY
				SELECT MAX(SALARY)
				FROM EMPLOYEES
				WHERE SALARY < (-- 2ND SUB QUREY
								SELECT MAX(SALARY)
								FROM EMPLOYEES
								)
                );
                
-- SECOND ONE IS WHICH OF THE EMPLOYEES GET MORE SALARY THEN  THERE MANAGER
-- MAIN QUERY 
SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > ( -- SUB QUERY
				SELECT SALARY
                FROM EMPLOYEES AS MNG
                WHERE EMP.MANAGER_ID = MNG.EMPLOYEE_ID
);


-- THIRD ONE IS WHICH EMPLOYEES WORK ON SAME SECTOR WHERE THE MANAGER DO 
-- MAIN QUERY 
SELECT *
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (-- SUB QUREY 
				SELECT JOB_ID
                FROM EMPLOYEES AS MNG
                WHERE EMP.MANAGER_ID = MNG.EMPLOYEE_ID
                );