-- NORMAL COMMON TABLE EXPRESSON (WITH AS)

-- SYNTAX
-- WITH TEMP AS(
-- SELECT *
-- FROM EMPLOYEES
-- LIMIT 5
-- )

-- SELECT *
-- FROM TEMP;


-- IN HERE WE SEE ONE EXAMPLE OF CTE
WITH AVGIT AS
(
  SELECT AVG(SALARY) AS VAL
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = 60

),
  MAXMKT AS
(
  SELECT MAX(SALARY) AS VAL
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = 20 
)

SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT VAL FROM AVGIT) AND SALARY <(SELECT VAL FROM MAXMKT)