# Generated by Django 4.2.7 on 2023-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carModel', '0002_alter_carmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(default='', upload_to='carModel/media/uploads'),
        ),
    ]
