CREATE DATABASE SCHOOLATTENDANCE;

USE SCHOOLATTENDANCEP;

CREATE TABLE TEACHER(
	TEACHER_ID VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR(50),
    EMAIL VARCHAR(100)
);

CREATE TABLE COURSE(
	COURSE_ID VARCHAR(20) PRIMARY KEY,
    COURSE_NAME VARCHAR(30),
    EMPLOYEE VARCHAR(5),
    
    CONSTRAINT EMPL FOREIGN KEY (EMPLOYEE) REFERENCES TEACHER(TEACHER_ID)
);


CREATE TABLE TOPIC(
	TOPIC_NAME VARCHAR(50) PRIMARY KEY,
    COURSE_ID VARCHAR(20),
    
    CONSTRAINT CRS_ID FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE LESSION(
	LESSION_ID VARCHAR(50) PRIMARY KEY,
    DATE_OF_LESSION DATE DEFAULT(current_date()),
    TIME_OF_LESSION TIME DEFAULT(current_time()),
    TOPIC_NAME VARCHAR(50),
     CONSTRAINT TPC_N FOREIGN KEY (TOPIC_NAME) REFERENCES TOPIC(TOPIC_NAME)
);

CREATE TABLE STUDENT(
	STUDENT_ID VARCHAR(5) PRIMARY KEY,
    STUDENT_NAME VARCHAR(50),
    CLASS_NAME  VARCHAR(2),
    LESSION_ID VARCHAR(50),
    
     CONSTRAINT LSN_ID FOREIGN KEY (LESSION_ID) REFERENCES LESSION(LESSION_ID)
);

CREATE TABLE ATTENDACNCE(
	ID_OF_THE_STD VARCHAR(5),
    ID_OF_THE_LSN VARCHAR(50),
	CONSTRAINT A_LSN_ID FOREIGN KEY (ID_OF_THE_LSN) REFERENCES LESSION(LESSION_ID),
    CONSTRAINT STD_ID FOREIGN KEY (ID_OF_THE_STD) REFERENCES STUDENT(STUDENT_ID)
);
