# Generated by Django 4.2.7 on 2023-12-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='birth_Data',
            new_name='birth_date',
        ),
    ]
