# Generated by Django 4.2.7 on 2024-01-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
        ('patient', '0002_alter_patient_user'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointmentd',
            new_name='Appointment',
        ),
    ]
