CREATE DATABASE SCHOOL_LIBRARY;
USE SCHOOL_LIBRARY;

CREATE TABLE STUDENT(
	STUDENT_ID VARCHAR(10) PRIMARY KEY,
    STUDENT_NAME VARCHAR(50) NOT NULL,
    STUDENT_CLASS VARCHAR(2)
);

CREATE TABLE BOOKS(
	BOOK_ID VARCHAR(10) PRIMARY KEY,
    BOOK_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE BROWED(
	WHO_BOROWED_ID VARCHAR(10),
    WHICH_BOOK_ID VARCHAR(10),
    BOOK_BROW_DATE DATE,
    
    CONSTRAINT WHO_ID FOREIGN KEY (WHO_BOROWED_ID) REFERENCES STUDENT(STUDENT_ID),
    CONSTRAINT BK_ID FOREIGN KEY (WHICH_BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    PRIMARY KEY(WHO_BOROWED_ID,WHICH_BOOK_ID)
);

CREATE TABLE MANAGER(
	MANAGER_ID VARCHAR(10) PRIMARY KEY,
    MANAGER_NAME VARCHAR(50) NOT NULL,
    DESIGNATION VARCHAR(20) 
);

CREATE TABLE AUTHOR(
	AUTHOR_ID VARCHAR(10) PRIMARY KEY,
    AUTHOR_NAME VARCHAR(40) NOT NULL,
    AUTHOR_ADRESS VARCHAR(100) 
);

CREATE TABLE PERMISSION(
	WHICH_BOOK_ID VARCHAR(10),
      CONSTRAINT PR_ID FOREIGN KEY (WHICH_BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
