# Generated by Django 4.2.7 on 2023-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoModes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fatherName',
            field=models.TextField(default='RofiQ'),
        ),
    ]
